version: '3.8'
services:


  customer-support-frontend:
    build: 
      context: ../../
      dockerfile: docker/prod/Dockerfile
      args:
        VITE_SOCKET_URL: https://www.dowellchat.uxlivinglab.online
    container_name: dowellcustomersupport-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/usr/src/app
      - ../../nginx/prod/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.dowellchat.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.dowellchat.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.dowellchat.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.dowellchat.uxlivinglab.online/privkey.pem:ro
    environment:
      VITE_SOCKET_URL: https://www.dowellchat.uxlivinglab.online
    restart: always
    networks:
      - webnet


networks:
    webnet:
        external: true
